name: 🛒 Generate Merch Rank JSON

on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours
  workflow_dispatch:

permissions:
 contents: write

jobs:
  update-merch-rank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate merch-rank.json
        run: node scripts/generate-rank.js
        env:
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN }}
          SHOPIFY_API_TOKEN: ${{ secrets.SHOPIFY_API_TOKEN }}

      - name: Commit and push updated merch-rank.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add merch-rank.json
          git commit -m "🛒 Update merch-rank.json" || echo "No changes to commit"
          git push
